---

- hosts: all
  sudo: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson 

- include: packages.yml
- include: users.yml
#- include: test.yml

#### Hardening should be the last step
- include: hardening.yml